# -*- coding: utf-8 -*-
"""NHIS2021_Chi_Sqr_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMgkKZ2Pf_s8Tzk1FTk_7O2B0Ww8Ax9W
"""

import numpy as np
import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/jihyunlee1007/NHIS2021_Project/main/chi.csv')
df = df.rename(columns={'Unnamed: 0': 'Question'})
df

def filtered(question):
    if question.startswith(('DEPANXFREQ_A7', 'DEPANXFREQ_A8', 'DEPANXFREQ_A9')):
        return False
    if question.endswith('-1'):
        return False
    if not question[-2:].isdigit() or int(question[-2:]) < 18:
        return False
    if 'RATCAT_A' in question:
        return False
    return True

filtered_df = df[df['Question'].apply(filtered)]

top_dep_p_values = filtered_df.sort_values(by='dep_p_value').head(10)
print("Top 10 highest values for dep_p_value:")
print(top_dep_p_values[['Question', 'dep_x_squared', 'dep_p_value']])

top_anx_p_values = filtered_df.sort_values(by='anx_p_value').head(10)
print("\nTop 10 highest values for anx_p_value:")
print(top_anx_p_values[['Question', 'anx_x_squared', 'anx_p_value']])
